export const adatLISTA = [
  {
    cim: "Skulduggery Pleasant",
    kep: "kepek/skulduggery_1.png",
    iro: "Derek Landy",
    mufaly: "fantasy",
    kiadasDatuma: 2007,
  },
  {
    cim: "Playing with Fire",
    kep: "kepek/skulduggery_2.png",
    iro: "Derek Landy",
    mufaly: "fantasy",
    kiadasDatuma: 2008,
  },
  {
    cim: "The Faceless Ones",
    kep: "kepek/skulduggery_3.png",
    iro: "Derek Landy",
    mufaly: "fantasy",
    kiadasDatuma: 2009,
  },
  {
    cim: "Dark Days",
    kep: "kepek/skulduggery_4.png",
    iro: "Derek Landy",
    mufaly: "fantasy",
    kiadasDatuma: 2010,
  },
  {
    cim: "Mortal Coil",
    kep: "kepek/skulduggery_5.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2010,
  },
  {
    cim: "Death Bringer",
    kep: "kepek/skulduggery_6.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2011,
  },
  {
    cim: "Kingdom of the Wicked",
    kep: "kepek/skulduggery_7.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2012,
  },
  {
    cim: "Last Stand of Dead Men",
    kep: "kepek/skulduggery_8.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2013,
  },
  {
    cim: "The Dying of the Light",
    kep: "kepek/skulduggery_9.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2014,
  },
  {
    cim: "Resurrection",
    kep: "kepek/skulduggery_10.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2017,
  },
  {
    cim: "Midnight",
    kep: "kepek/skulduggery_11.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2018,
  },
  {
    cim: "Bedlam",
    kep: "kepek/skulduggery_12.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2019,
  },
  {
    cim: "Seasons of War",
    kep: "kepek/skulduggery_13.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2020,
  },
  {
    cim: "Dead or Alive",
    kep: "kepek/skulduggery_14.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2021,
  },
  {
    cim: "Until the End",
    kep: "kepek/skulduggery_15.png",
    iro: "Derek Landy",
    mufaly: "dark fantasy",
    kiadasDatuma: 2022,
  },
];
